import type { Metadata } from "next";
import { Bowlby_One_SC, DM_Mono } from "next/font/google";
import "./globals.css";

const Bowlby = Bowlby_One_SC({
  variable: "--font-Bowlby_One_SC",
  subsets: ["latin"],
  weight: "400",
  display: "swap"
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: "500",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Bowlby.variable} ${dmMono.variable} antialiased dm-mono font-medium text-zinc-800`} 
      >
        {children}
      </body>
    </html>
  );
}